project:
  type: website

website:
  title: "HCP Intro to R Bootcamp"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Session Materials"
        file: notebooks/sessions.qmd
      - text: "Resources"
        file: resources/resources.qmd
        
  sidebar:
    - title: "Session Materials"
      contents:
        - notebooks/sessions.qmd
        - notebooks/session1.qmd
        - notebooks/session2.qmd
        - notebooks/session3.qmd
        - notebooks/session4.qmd
        - notebooks/session5.qmd

    - title: "Resources"
      contents:
        - resources/install.qmd
        - resources/resources.qmd
        - resources/getting-help.qmd
        # navigation items

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
    anchor-sections: false
#  pdf: 
#    prefer-html: false
